"""Canonical ``iac/``-tree content hash + the ``c6.v1`` sidecar schema (Phase C6).

This is the single source of truth for the Phase-C6 head-config-delivery gate. The
``iac/``-tree hash binds *the config the worker is baked from* to *the config the
operator reviewed + approved in the PR head*, surviving the squash-merge (which
changes the merged-``main`` commit SHA but NOT the ``iac/`` tree content — the
``iac.yml`` diff-guard proves the PR touches only ``iac/``).

It is computed **identically** by two callers, so a re-baked-from-``main`` worker can
prove byte-for-byte fidelity to the approved head:

- ``tools/iac_tree_hash.py`` — the C2 plan-builder, over the checked-out ``iac/``;
- the ``workers/tofu_apply`` worker — over its baked ``IAC_DIR`` (committed files +
  a regenerated ``.terraform/`` from the bake's ``tofu init``, plus ``plan.tfplan``
  written in at apply time).

For the two sides to agree, the exclude set MUST drop exactly the generated /
non-committed files (``.terraform/``, the C2/apply artifacts, tfstate). A divergence
between the two sides is almost always an OVER-refusal (the fail-closed direction); a
false-clean would require a broken hash definition. The module lives in
``driftscribe_lib`` (not ``tools``) so the worker container — which ships
``driftscribe_lib/`` but NOT ``tools/`` — can import it.

See docs/plans/2026-05-31-infra-iac-phase-c6-head-config-delivery.md §3.1/§3.2.
DO NOT change the exclude set without bumping :data:`SIDECAR_SCHEMA_VERSION` AND
re-baking the worker (the two sides must move in lockstep).
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

__all__ = [
    "SIDECAR_SCHEMA_VERSION",
    "IacTreeHashError",
    "iac_tree_hash",
    "SidecarInput",
    "build_sidecar",
    "serialize_sidecar",
]

SIDECAR_SCHEMA_VERSION = "c6.v1"

# Generated / non-committed files dropped from the hash — the byte-identical contract
# between the C2 git checkout and the Docker bake. DO NOT change without bumping
# SIDECAR_SCHEMA_VERSION AND re-baking.
#   - ``.terraform/`` — provider cache, regenerated by the bake's ``tofu init`` (so it
#     differs from C2's, and may contain its own symlinks → pruned, never traversed).
#   - the C2/apply artifacts that C2 writes INTO ``iac/`` (``plan.tfplan`` etc.) — at
#     the ``iac/`` ROOT only, so a (hypothetical) committed nested file of the same
#     name is still hashed.
#   - ``*.tfstate`` / ``*.tfstate.backup`` — never present with the remote backend,
#     excluded defensively anywhere.
_EXCLUDED_ROOT_ARTIFACTS = frozenset(
    {"plan.tfplan", "plan.json", "metadata.json", "iac-tree.json"}
)


class IacTreeHashError(ValueError):
    """Fail-closed: a symlink or non-regular file under ``iac/`` (outside the pruned
    ``.terraform/``). C2 (a git checkout) and the Docker bake can resolve a symlink
    differently, so a silently-followed link is a hash-divergence foot-gun; an
    agent-mode PR only ever adds plain ``.tf`` files, so a symlink is already
    anomalous. Subclasses ``ValueError`` so existing fail-closed ``except ValueError``
    refusal handlers in the worker treat it as a clean refusal, never a 500."""


def _is_excluded_dir(rel: str) -> bool:
    """Directories pruned from the walk. ONLY ``.terraform/`` — the provider cache the
    bake regenerates. A directory that merely shares an artifact basename
    (``plan.json/``, ``foo.tfstate/``) is NOT pruned: it is committed config and its
    files must be hashed (Codex C6a-1 import 2 — split file-vs-dir exclusion)."""
    return rel == ".terraform" or rel.startswith(".terraform/")


def _is_excluded_file(rel: str) -> bool:
    """Files dropped from the hash: anything under the pruned ``.terraform/`` (defensive
    — the dir prune already prevents descent), the C2/apply artifacts at the ``iac/``
    ROOT only (so a committed ``nested/plan.json`` is still hashed), and ``*.tfstate``
    anywhere (defensive)."""
    if rel.startswith(".terraform/"):
        return True
    if rel in _EXCLUDED_ROOT_ARTIFACTS:
        return True
    base = rel.rsplit("/", 1)[-1]
    return base.endswith(".tfstate") or base.endswith(".tfstate.backup")


def iac_tree_hash(iac_dir: str | os.PathLike[str]) -> str:
    """Return the canonical content hash of the committed ``iac/`` tree.

    Walks ``iac_dir`` with ``os.walk(followlinks=False)`` (never descends a symlinked
    dir), prunes ``.terraform/`` BEFORE the symlink check (so provider-plugin symlinks
    inside it don't raise), and fails closed (:class:`IacTreeHashError`) on a missing /
    non-directory / symlinked ``iac_dir`` (a hash gate must NOT silently treat a
    missing path as the empty tree — Codex C6a-1 import 1), and on any non-excluded
    symlink or non-regular file. The digest folds ``rel_posix_path \\0 sha256(content)
    \\0`` over entries sorted by path — deterministic and independent of filesystem
    walk order. File modes are NOT hashed (OpenTofu ignores them; git/Docker differ).
    Empty committed dirs are invisible (git doesn't track them either — symmetric on
    both sides)."""
    root = Path(iac_dir)
    if os.path.islink(root):
        raise IacTreeHashError(f"iac dir is itself a symlink: {root}")
    if not root.is_dir():
        raise IacTreeHashError(f"iac dir not found or not a directory: {root}")
    entries: list[tuple[str, str]] = []

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        rel_dir = Path(dirpath).relative_to(root).as_posix()

        # Prune excluded / symlinked subdirs IN PLACE so os.walk never descends them.
        kept: list[str] = []
        for d in dirnames:
            rel = d if rel_dir == "." else f"{rel_dir}/{d}"
            if _is_excluded_dir(rel):
                continue  # .terraform/ — never traversed (its symlinks ignored)
            if os.path.islink(os.path.join(dirpath, d)):
                raise IacTreeHashError(f"symlink directory under iac/ not allowed: {rel}")
            kept.append(d)
        dirnames[:] = kept

        for f in filenames:
            rel = f if rel_dir == "." else f"{rel_dir}/{f}"
            if _is_excluded_file(rel):
                continue
            full = os.path.join(dirpath, f)
            if os.path.islink(full):
                raise IacTreeHashError(f"symlink under iac/ not allowed: {rel}")
            if not os.path.isfile(full):
                raise IacTreeHashError(f"non-regular file under iac/: {rel}")
            entries.append((rel, hashlib.sha256(Path(full).read_bytes()).hexdigest()))

    entries.sort()
    h = hashlib.sha256()
    for rel, digest in entries:
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        h.update(digest.encode("ascii"))
        h.update(b"\x00")
    return h.hexdigest()


# --------------------------------------------------------------------------- #
# The c6.v1 sidecar schema (mirrors driftscribe_lib.iac_plan_metadata)
# --------------------------------------------------------------------------- #

_HEX40 = re.compile(r"^[0-9a-f]{40}$")
_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_REPO = re.compile(r"^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$")
_DIGITS = re.compile(r"^[0-9]+$")
_POSITIVE_DIGITS = re.compile(r"^[1-9][0-9]*$")


@dataclass(frozen=True)
class SidecarInput:
    """Input to :func:`build_sidecar`. All fields required. Every field except
    ``iac_tree_hash`` MUST equal the matching ``c2.v1`` metadata field, so the worker
    can cross-check the sidecar against the HMAC-signed metadata before trusting the
    hash (the sidecar itself is unsigned; integrity comes from that cross-check +
    bucket IAM)."""

    repo: str
    pr_number: int
    head_sha: str
    base_sha: str
    workflow_run_id: str
    workflow_run_attempt: str
    plan_sha256: str
    plan_json_sha256: str
    iac_tree_hash: str


def _check(name: str, value: Any, predicate, message: str) -> None:
    if not predicate(value):
        raise ValueError(f"{name}: {message} (got {value!r})")


def build_sidecar(inp: SidecarInput) -> dict[str, Any]:
    """Validate input + return the sidecar dict. Raises ``ValueError`` on any
    malformed field; NEVER returns a partial record."""
    _check("repo", inp.repo, lambda v: bool(_REPO.fullmatch(v)), "must be 'owner/repo'")
    _check(
        "pr_number", inp.pr_number,
        lambda v: isinstance(v, int) and not isinstance(v, bool) and v > 0,
        "must be a positive int",
    )
    _check("head_sha", inp.head_sha, lambda v: bool(_HEX40.fullmatch(v)), "must be 40 lowercase hex")
    _check("base_sha", inp.base_sha, lambda v: bool(_HEX40.fullmatch(v)), "must be 40 lowercase hex")
    _check(
        "workflow_run_id", inp.workflow_run_id,
        lambda v: isinstance(v, str) and bool(_DIGITS.fullmatch(v)),
        "must be a numeric string",
    )
    _check(
        "workflow_run_attempt", inp.workflow_run_attempt,
        lambda v: isinstance(v, str) and bool(_POSITIVE_DIGITS.fullmatch(v)),
        "must be a positive numeric string (GHA run_attempt is 1-indexed)",
    )
    _check("plan_sha256", inp.plan_sha256, lambda v: bool(_HEX64.fullmatch(v)), "must be 64 lowercase hex")
    _check("plan_json_sha256", inp.plan_json_sha256, lambda v: bool(_HEX64.fullmatch(v)), "must be 64 lowercase hex")
    _check("iac_tree_hash", inp.iac_tree_hash, lambda v: bool(_HEX64.fullmatch(v)), "must be 64 lowercase hex")

    return {
        "schema_version": SIDECAR_SCHEMA_VERSION,
        "repo": inp.repo,
        "pr_number": inp.pr_number,
        "head_sha": inp.head_sha,
        "base_sha": inp.base_sha,
        "workflow_run_id": inp.workflow_run_id,
        "workflow_run_attempt": inp.workflow_run_attempt,
        "plan_sha256": inp.plan_sha256,
        "plan_json_sha256": inp.plan_json_sha256,
        "iac_tree_hash": inp.iac_tree_hash,
    }


def serialize_sidecar(sidecar: dict[str, Any]) -> str:
    """Stable canonical JSON encoding — sorted keys, 2-space indent, trailing newline."""
    return json.dumps(sidecar, sort_keys=True, indent=2) + "\n"
