from agent.models import DecisionProposal, EnvDiff
from agent.secret_guard import should_redact, value_looks_credentialed

_REDACTED = "`(value redacted: secret-like)`"


def _escape_markdown_cell(s: str) -> str:
    """Escape characters that would break a markdown table cell.

    - `|` is escaped (column separator).
    - Backticks are escaped (closes inline-code span).
    - CR/LF are replaced with the literal text ``\\n`` so a multi-line value
      doesn't shatter the row.
    """
    return (
        s.replace("\r\n", "\\n")
        .replace("\n", "\\n")
        .replace("\r", "\\n")
        .replace("|", "\\|")
        .replace("`", "\\`")
    )


def _format_value_cell(name: str, value: str | None) -> str:
    """Render a value cell. Redacts when name is secret-like OR value looks
    like a credential (e.g. URL with ``user:pass@`` authority).

    Empty string is NOT collapsed to "—" — an empty live value is a real drift
    signal (var was explicitly unset) and must be distinguishable from missing.
    """
    if should_redact(name, value):
        return _REDACTED if value is not None else "`—`"
    if value is None:
        return "`—`"
    return f"`{_escape_markdown_cell(value)}`"


def _format_name_cell(name: str) -> str:
    return f"`{_escape_markdown_cell(name)}`"


def _format_pr_cell(name: str, url: str | None, diff_values: tuple[str | None, ...]) -> str:
    if url is None:
        return "—"
    # Redact if name is secret-like, value looks credentialed, or the URL itself
    # carries credentials (e.g. ?token=...).
    if should_redact(name, url) or any(value_looks_credentialed(v) for v in diff_values):
        return "(redacted)"
    return _escape_markdown_cell(url)


def _diff_row(d: EnvDiff) -> str:
    return (
        f"| {_format_name_cell(d.name)} | {_format_value_cell(d.name, d.expected)} | "
        f"{_format_value_cell(d.name, d.live)} | "
        f"`{d.contract_status.value}` | "
        f"{_format_pr_cell(d.name, d.recent_pr_match, (d.expected, d.live, d.debug_config_value))} | "
        f"{_format_value_cell(d.name, d.debug_config_value)} |"
    )


def _evidence_table(proposal: DecisionProposal) -> str:
    header = "| Var | Expected | Live | Status | Recent PR | /debug/config |\n|---|---|---|---|---|---|"
    rows = "\n".join(_diff_row(d) for d in proposal.env_diffs)
    return f"{header}\n{rows}"


def _scrub_secret_values_from_rationale(rationale: str, diffs: list[EnvDiff]) -> str:
    """If the LLM rationale string contains any sensitive value, replace it
    with a redaction marker. Sensitive = value from a secret-named var, or
    a credentialed URL, or any recent_pr_match URL for a secret-named var.

    Defense-in-depth against the LLM quoting the actual secret in prose.
    """
    scrubbed = rationale
    seen: set[str] = set()

    def _scrub(v: str | None) -> None:
        nonlocal scrubbed
        if v and v not in seen and len(v) >= 4:
            scrubbed = scrubbed.replace(v, "(redacted)")
            seen.add(v)

    for d in diffs:
        for v in (d.expected, d.live, d.debug_config_value):
            if should_redact(d.name, v):
                _scrub(v)
        # PR URL for a secret-named var (it might appear in rationale prose too)
        if should_redact(d.name, d.recent_pr_match):
            _scrub(d.recent_pr_match)
    return scrubbed


def render_docs_pr_body(p: DecisionProposal) -> str:
    rationale = _scrub_secret_values_from_rationale(p.rationale, p.env_diffs)
    return f"""\
## DriftScribe — sanctioned change detected

{rationale}

### Changes

{_evidence_table(p)}

### Confidence

{p.confidence:.2f}

> Generated by DriftScribe. The change appears sanctioned per `ops-contract.yaml`.
> Please review and merge to keep documentation in sync with production.
"""


def render_drift_issue_body(p: DecisionProposal) -> str:
    rationale = _scrub_secret_values_from_rationale(p.rationale, p.env_diffs)
    return f"""\
## DriftScribe — unsanctioned production drift

{rationale}

### Drift

{_evidence_table(p)}

### Recommended action

- Investigate why production differs from the operational contract.
- If the change is intentional, update `ops-contract.yaml` (set `allow_manual_change: true` and provide an `operator_note`, or revise `value`) and re-run DriftScribe.
- If the change is **not** intentional, roll back via `gcloud run services update --update-env-vars`.

> DriftScribe will not update documentation while the contract is violated.
"""


def render_rollback_body(p: DecisionProposal, approval_url: str) -> str:
    """Render the operator-facing approval body for a ROLLBACK decision.

    Delivered by the Notifier worker (severity="approval"). The body surfaces
    the approval URL minted by the Rollback Worker's ``/propose`` response so
    the operator can click through to ``{COORDINATOR_URL}/approvals/{id}`` and
    Approve / Reject the proposed traffic shift.

    ``approval_url`` is passed in (not derived) because the renderer is a pure
    function — it has no access to Firestore or the HMAC key, and the worker
    response is the only place the URL is minted. The caller (Task 13.3) reads
    ``result["approval_url"]`` from the worker response and threads it here.

    Markdown discipline:
    - The approval URL is wrapped in ``<...>`` (markdown autolink form) so
      long URLs don't line-break in some renderers.
    - ``target_revision`` is shown inside an inline code span — Cloud Run
      revision names are alphanumeric + hyphens, so they don't break tables.
    - The rationale is scrubbed via :func:`_scrub_secret_values_from_rationale`
      so an LLM that quoted a secret value in prose doesn't leak it here.
    """
    rationale = _scrub_secret_values_from_rationale(p.rationale, p.env_diffs)
    return f"""\
## DriftScribe — rollback proposed (approval required)

{rationale}

### Rollback details

- **Service:** `payment-demo`
- **Target revision:** `{p.target_revision}`
- **Reason:** hard contract violation — see rationale above and the evidence
  table below.

### Evidence

{_evidence_table(p)}

### Operator approval required

Click to review and approve / reject the rollback:

<{approval_url}>

This approval link expires in 15 minutes. After expiry, DriftScribe must
re-propose to mint a fresh token.

> Approving this rollback will swing **100% of traffic** on `payment-demo`
> to revision `{p.target_revision}`. Rejecting leaves traffic on the current
> revision and DriftScribe will not retry automatically.
"""


def render_escalation_issue_body(p: DecisionProposal) -> str:
    rationale = _scrub_secret_values_from_rationale(p.rationale, p.env_diffs)
    return f"""\
## DriftScribe — uncertain change requires review

{rationale}

### Observed (no contract entry, no recent PR mention)

{_evidence_table(p)}

### What I don't know

I observed variables in production that are **not in the operational contract**, and I could not find a recent merged PR that mentions them by exact name. I need a human to confirm intent before I touch documentation.

### Reviewer action

- If this change was intentional: add the var(s) to `ops-contract.yaml` with the appropriate `allow_manual_change` and `operator_note`, then re-run DriftScribe.
- If this change was unauthorized: roll back the affected Cloud Run service, then re-run DriftScribe.

> Generated by DriftScribe.
"""
