"""Tests for driftscribe_lib.iac_tree.iac_tree_hash — the canonical iac/-tree
content hash (Phase C6a-1).

The hash is computed IDENTICALLY by the C2 plan-builder (over the checked-out iac/)
and the tofu-apply worker (over its baked IAC_DIR), so a re-baked-from-main worker
can prove byte-for-byte fidelity to the approved PR head. These tests pin the
load-bearing properties: determinism, the exact exclude set (so generated files on
one side don't diverge the hash), path-binding, and fail-closed symlink handling.
"""

import hashlib

import pytest

from driftscribe_lib import iac_tree
from driftscribe_lib.iac_tree import IacTreeHashError, iac_tree_hash


def _write(root, rel, content=b"x"):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(content if isinstance(content, bytes) else content.encode())
    return p


def test_module_imports():
    assert iac_tree is not None


def test_empty_dir_is_stable(tmp_path):
    """An empty iac/ hashes to the empty-stream digest, deterministically."""
    a = tmp_path / "a"
    b = tmp_path / "b"
    a.mkdir()
    b.mkdir()
    assert iac_tree_hash(a) == iac_tree_hash(b)
    assert iac_tree_hash(a) == hashlib.sha256().hexdigest()


def test_deterministic_same_content_same_hash(tmp_path):
    """Two trees with identical committed content hash equal, regardless of the
    order files were created in."""
    a = tmp_path / "a"
    b = tmp_path / "b"
    _write(a, "main.tf", "resource x {}")
    _write(a, "sub/extra.tf", "y")
    # create b in the opposite order
    _write(b, "sub/extra.tf", "y")
    _write(b, "main.tf", "resource x {}")
    assert iac_tree_hash(a) == iac_tree_hash(b)


def test_content_change_changes_hash(tmp_path):
    a = tmp_path / "a"
    _write(a, "main.tf", "one")
    h1 = iac_tree_hash(a)
    (a / "main.tf").write_text("two")
    assert iac_tree_hash(a) != h1


def test_lockfile_is_included(tmp_path):
    """.terraform.lock.hcl is committed + material → it IS hashed."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    h1 = iac_tree_hash(a)
    _write(a, ".terraform.lock.hcl", "provider pins")
    assert iac_tree_hash(a) != h1


def test_path_is_bound_not_just_content(tmp_path):
    """Same bytes at a different path → different hash (the path is folded in)."""
    a = tmp_path / "a"
    b = tmp_path / "b"
    _write(a, "main.tf", "same")
    _write(b, "other.tf", "same")
    assert iac_tree_hash(a) != iac_tree_hash(b)


@pytest.mark.parametrize(
    "rel",
    [
        ".terraform/providers/registry/google/terraform-provider-google",
        ".terraform/plugin_cache",
        "plan.tfplan",
        "plan.json",
        "metadata.json",
        "iac-tree.json",
        "terraform.tfstate",
        "terraform.tfstate.backup",
    ],
)
def test_generated_files_are_excluded(tmp_path, rel):
    """Files generated by C2 / the bake / apply (and never committed) must NOT
    change the hash — they exist on one side (worker baked .terraform/, C2's
    plan.json) but not the other, so hashing them would always diverge."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    base = iac_tree_hash(a)
    _write(a, rel, "GENERATED — should be ignored")
    assert iac_tree_hash(a) == base


def test_terraform_dir_with_symlink_is_not_traversed(tmp_path):
    """A symlink INSIDE the excluded .terraform/ (provider plugins are often
    symlinked) must be skipped, never raise — .terraform/ is pruned before the
    symlink check."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    base = iac_tree_hash(a)
    tfdir = a / ".terraform" / "providers"
    tfdir.mkdir(parents=True)
    target = a / ".terraform" / "real"
    target.write_text("plugin")
    (tfdir / "link").symlink_to(target)
    assert iac_tree_hash(a) == base


def test_symlink_file_under_iac_raises(tmp_path):
    """A committed-config-area symlink is anomalous (git vs Docker resolve it
    differently) → fail closed."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    (a / "evil.tf").symlink_to(a / "main.tf")
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(a)


def test_symlinked_dir_under_iac_raises(tmp_path):
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    real = tmp_path / "outside"
    real.mkdir()
    (real / "secret.tf").write_text("s")
    (a / "linkdir").symlink_to(real, target_is_directory=True)
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(a)


def test_nested_committed_files_are_hashed(tmp_path):
    """Non-excluded nested files DO count (e.g. a committed modules-free sub.tf)."""
    a = tmp_path / "a"
    b = tmp_path / "b"
    _write(a, "main.tf", "x")
    _write(b, "main.tf", "x")
    _write(b, "nested/sub.tf", "deep")
    assert iac_tree_hash(a) != iac_tree_hash(b)


@pytest.mark.parametrize(
    "rel",
    ["nested/plan.json", "nested/metadata.json", "nested/iac-tree.json", "nested/plan.tfplan"],
)
def test_nested_artifact_basenames_are_included(tmp_path, rel):
    """The artifact exclusion is ROOT-only — a committed file that merely shares an
    artifact basename DEEPER in the tree is still hashed (Codex C6a-1 import 3)."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    base = iac_tree_hash(a)
    _write(a, rel, "committed-not-generated")
    assert iac_tree_hash(a) != base


def test_directory_named_like_an_artifact_is_traversed(tmp_path):
    """A DIRECTORY sharing an artifact basename is NOT pruned (only .terraform/ is) —
    its files are hashed (Codex C6a-1 import 2: split file-vs-dir exclusion)."""
    a = tmp_path / "a"
    _write(a, "main.tf", "x")
    base = iac_tree_hash(a)
    _write(a, "plan.json/inner.tf", "real config under an oddly-named dir")
    assert iac_tree_hash(a) != base


def test_missing_dir_raises_not_empty_hash(tmp_path):
    """A hash gate must fail closed on a missing path, NOT return the empty-tree
    hash (Codex C6a-1 import 1)."""
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(tmp_path / "does-not-exist")


def test_file_path_raises(tmp_path):
    f = tmp_path / "afile"
    f.write_text("x")
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(f)


def test_symlinked_iac_dir_itself_raises(tmp_path):
    real = tmp_path / "real"
    real.mkdir()
    (real / "main.tf").write_text("x")
    link = tmp_path / "link"
    link.symlink_to(real, target_is_directory=True)
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(link)


def test_oserror_during_read_is_wrapped_fail_closed(tmp_path, monkeypatch):
    """A read failure (e.g. a TOCTOU delete between os.walk and read_bytes, or a
    permission anomaly) must surface as IacTreeHashError — NOT a raw OSError that
    escapes the worker gate and 500-strands a burned approval (adversarial review)."""
    _write(tmp_path, "main.tf", "x")

    import pathlib
    orig = pathlib.Path.read_bytes

    def boom(self):
        if self.name == "main.tf":
            raise PermissionError("vanished")
        return orig(self)

    monkeypatch.setattr(pathlib.Path, "read_bytes", boom)
    with pytest.raises(IacTreeHashError):
        iac_tree_hash(tmp_path)
